#强化插件配置文件
# 剑的每级伤害（近战）
sword: 1.5
# 弓箭的每级伤害
bow: 1.5
# 弩的每级伤害
crossbow: 1.3
# 护甲强化一级抵抗的伤害数值
defence: 0.5
# 当防御伤害高于攻击伤害（强化等级过高导致不掉血的刮痧伤害）
min_damage: 1
strength_stone:
  stone_normal:
    #配置物品类型
    item: SPONGE
    #配置强化石名字
    name: '&b强化石'
    #配置强化石lore，允许多行lore
    lore:
      - '&a用于强化武器和防具的好东西'
  stone_safe:
    # 允许填入物品类型
    item: PAPER
    name: '&c保护强化卷'
    # 配置是否允许保护石进行保护
    safe: true
    lore:
      - '&b用于保护超过&c[&a8&c]&b级之后的强化不导致武器破碎'
  stone_success:
    item: EMERALD
    name: '&e必定成功强化石'
    # 配置是否允许必定成功石成功
    success: true
    lore:
      - '&6必定成功的强化石，只要使用它，那么这次强化必定会成功'
# 强化几率，总共十级，如果超出不会读取
strength_chance:
  - 100
  - 90
  - 80
  - 70
  - 60
  - 50
  - 40
  - 30
  - 20
  - 10
#强化名称，必须要对的上物品名
itemName:
  - 'WOODEN_SWORD'
  - 'STONE_SWORD'
  - 'IRON_SWORD'
  - 'GOLDEN_SWORD'
  - 'DIAMOND_SWORD'
  - 'NETHERITE_SWORD'
  - 'WOODEN_AXE'
  - 'STONE_AXE'
  - 'IRON_AXE'
  - 'GOLDEN_AXE'
  - 'DIAMOND_AXE'
  - 'NETHERITE_AXE'
  - 'BOW'
  - 'CROSSBOW'
  - 'DIAMOND_HELMET'
  - 'DIAMOND_CHESTPLATE'
  - 'DIAMOND_LEGGINGS'
  - 'DIAMOND_BOOTS'
  - 'NETHERITE_HELMET'
  - 'NETHERITE_CHESTPLATE'
  - 'NETHERITE_LEGGINGS'
  - 'NETHERITE_BOOTS'
  - 'IRON_HELMET'
  - 'IRON_CHESTPLATE'
  - 'IRON_LEGGINGS'
  - 'IRON_BOOTS'
  - 'GOLDEN_HELMET'
  - 'GOLDEN_CHESTPLATE'
  - 'GOLDEN_LEGGINGS'
  - 'GOLDEN_BOOTS'
